afr_module( NAME tensor_flow )

set(TENSOR_FLOW_DIR ${CMAKE_CURRENT_LIST_DIR}/tensorflow_src)

set(include_dirs
${TENSOR_FLOW_DIR}
${TENSOR_FLOW_DIR}/tensorflow/lite
${TENSOR_FLOW_DIR}/tensorflow/lite/c
${TENSOR_FLOW_DIR}/tensorflow/lite/core/api
${TENSOR_FLOW_DIR}/tensorflow/lite/kernels
${TENSOR_FLOW_DIR}/tensorflow/lite/kernels/internal
${TENSOR_FLOW_DIR}/tensorflow/lite/micro
${TENSOR_FLOW_DIR}/tensorflow/lite/micro/benchmarks
${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels
${TENSOR_FLOW_DIR}/tensorflow/lite/kernels/internal
${TENSOR_FLOW_DIR}/tensorflow/lite/kernels/internal/reference
${TENSOR_FLOW_DIR}/tensorflow/lite/kernels/internal/reference/integer_ops
${TENSOR_FLOW_DIR}/tensorflow/lite/kernels/internal/optimized
${TENSOR_FLOW_DIR}/tensorflow/lite/micro/memory_planner
${TENSOR_FLOW_DIR}/tensorflow/lite/micro/testing
${TENSOR_FLOW_DIR}/tensorflow/lite/schema
${TENSOR_FLOW_DIR}/tensorflow/core
${TENSOR_FLOW_DIR}/third_party/flatbuffers/include
${TENSOR_FLOW_DIR}/third_party/gemmlowp
${TENSOR_FLOW_DIR}/third_party/gemmlowp/fixedpoint
${TENSOR_FLOW_DIR}/third_party/gemmlowp/internal
${TENSOR_FLOW_DIR}/third_party/kissfft
${TENSOR_FLOW_DIR}/third_party/kissfft/tools
${TENSOR_FLOW_DIR}/third_party/ruy
)

set(srcs
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/simple_memory_allocator.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/all_ops_resolver.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/memory_helpers.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/recording_micro_allocator.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/micro_error_reporter.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/micro_time.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/recording_simple_memory_allocator.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/micro_string.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/micro_profiler.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/micro_utils.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/micro_optional_debug_tools.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/debug_log.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/test_helpers.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/micro_interpreter.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/micro_allocator.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/benchmarks/keyword_scrambled_model_data.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/strided_slice.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/prelu.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/dequantize.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/ethosu.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/l2norm.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/tanh.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/activations.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/logistic.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/arg_min_max.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/pad.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/reduce.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/floor.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/conv.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/unpack.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/fully_connected.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/add.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/split.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/softmax.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/circular_buffer.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/svdf.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/sub.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/concatenation.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/round.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/ceil.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/elementwise.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/mul.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/maximum_minimum.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/pooling.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/neg.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/pack.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/logical.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/quantize.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/comparisons.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/reshape.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/kernels/depthwise_conv.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/memory_planner/linear_memory_planner.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/memory_planner/greedy_memory_planner.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/testing/test_conv_model.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/c/common.c"
"${TENSOR_FLOW_DIR}/tensorflow/lite/core/api/error_reporter.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/core/api/flatbuffer_conversions.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/core/api/op_resolver.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/core/api/tensor_utils.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/kernels/internal/quantization_util.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/kernels/kernel_util.cc"
"${TENSOR_FLOW_DIR}/tensorflow/lite/micro/testing/test_utils.cc")


afr_module_sources(
    ${AFR_CURRENT_MODULE}
    PRIVATE
    ${srcs}
)

afr_module_include_dirs(
    ${AFR_CURRENT_MODULE}
    PUBLIC
    ${include_dirs}
)